[package]
name = "kristforge"
version = "3.1.6"
description = "Hardware accelerated CPU and GPU Krist miner"
authors = ["Dana Marcuse <dana@marcuse.us>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
array-init = "2.0.1"
crossbeam = "0.7.3"
dirs = "3.0.1"
dynamic_ocl = "0.1.0-alpha.1"
enumset = "1.0.1"
futures = "0.3.5"
hex = "0.4.2"
indicatif = "0.15.0"
isahc = { version = "0.9.8", features = [ "static-ssl" ] }
itertools = "0.9.0"
lazy_static = "1.4.0"
log = "0.4.11"
num_cpus = "1.13.0"
rand = "0.7.3"
ring = "0.16.15"
serde = { version = "1.0.115", features = [ "derive" ] }
serde_json = "1.0.57"
sha2 = { version = "0.10.2", features = [ "asm", "compress" ] }
simplelog = "0.8.0"
structopt = "0.3.16"
thiserror = "1.0.20"
tokio = { version = "0.2.22", features = [ "macros" ] }
tokio-tungstenite = { version = "0.11.0", features = [ "tls" ] }
url = { version = "2.1.1", features = [ "serde" ] }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[target.'cfg(unix)'.dependencies]
libc = "0.2.74"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
debug = true

[profile.release.package."*"]
codegen-units = 1
debug = false

[profile.dev.package."*"]
opt-level = 1
codegen-units = 1
